<!-- <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
<div class="flex items-center justify-center min-h-screen bg-gray-100">
    <div class="px-8 py-6 mt-4 text-left bg-white shadow-lg">
        <h3 class="text-2xl font-bold text-center">Login to your account</h3>
        <form action="/frontend/productlist/list/" method="post">
            <div class="mt-4">
                <div>
                    <label class="block" for="email">Email<label>
                            <input type="text" placeholder="Email" name="email"
                                class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600">
                </div>
                <div class="mt-4">
                    <label class="block">Role<label>
                            <input type="text" placeholder="Role" name="role"
                                class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600">
                </div>
                <div class="mt-4">
                    <label class="block">Password<label>
                            <input type="password" placeholder="Password" name="password"
                                class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600">
                </div>
                <div class="flex items-baseline justify-between">
                    <button class="px-6 py-2 mt-4 text-white bg-blue-600 rounded-lg hover:bg-blue-900">Login</button>
                    <!-- <a href="#" class="text-sm text-blue-600 hover:underline">Forgot password?</a> 
                </div>
            </div>
        </form>
    </div>
</div> -->


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@200;700&family=Poppins&display=swap');


h1
{
  text-align:center;
  padding: 0;
  margin:0;
  text-align: center;
}

label
{
  background-color: rgb;
  padding: 2px;
  
}

body
{
  margin: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background-color: #7f53ac;
  background-image: linear-gradient(315deg, #7f53ac 0%, #647dee 74%);
  font-family: 'Inter';
}


#window
{
    margin-left: 500px;;
  background-color: white;
  padding: 6rem 5rem 6rem 5rem;
  border-radius: 6px;
  width: 400px;
  min-width: 20px;
  box-shadow: 5px 5px 15px black;
}

#LoginBtn
{
  width: 100%;
  padding: .5rem;
  background-color: black;
  color: white;
  font-size: 1rem;
  cursor:pointer;
  font-weight: 600;
  border: solid black 2px;
  font-family: 'Inter';
  border-radius: 1.5px;
  transition: .4s;
  
 }

#LoginBtn:hover
{
  color: black;
  background-color: white;
  border: solid black 2px;
  background-color: rgba(156, 156, 156, 0.24);
}

input
{
  width: 100%;
  border: none;
  border-bottom: black solid 1px;
  font-size: 1.1rem;
  padding: 0;
}

input:focus
{
  background-color: rgba(156, 156, 156, 0.12);
  border-bottom: black solid 1px;
}

*:focus
{
  outline: none;
  border: none;
}

.data
{
  padding: 0;
  width: 100%;
}

a {
  text-align: center;
  font-family: monospace;
  font-size: 1rem;
}
</style>
</head>
<body>
<div id="tsparticles"></div>
<form action="/frontend/productlist/list/" method="post">
<div id="window">
  <h1> Login </h1>
   <br>
   <br>
   <br>
  <div class="data"> 
  <label for="email">
    <br>
    <input id="email" type="text" name="email" placeholder="email">
  </label>
   <br>
   <br>
   <br>
   <div class="data"> 
  <label for="role">
    <br>
    <input id="role" type="text" name="role" placeholder="role">
  </label>
   <br>
   <br>
   <br>

   <label for ="user-pin">

    <br>
    <input type="password" id ="user-pin" name="password" placeholder="Password">
     <br>
     <br>
     <br>
     <button id="LoginBtn" name="submit" type="submit"> Login </button>
     
     <br>
     <br>
     <br>
     <div style="text-align: center;">
      <a href="#"> password forgotten? </a>
     </div>
    </label>
   </div>
   
   
  </div>
</form>
    
</body>

</html>

